version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - app-network

  oj_backend:
    build:
      context: ./oj_backend
    ports:
      - "8004:8004"
    networks:
      - app-network
    depends_on:
      - nginx

  oj_evaluate:
    build:
      context: ./oj_evaluate
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge
