version: '3'
services:
  oj-backend:
    build:
      context: ./oj_backend
    env_file:
      - .env
    ports:
      - "8001:8001"  # Expose service1 to the host
    networks:
      - app-network
    depends_on:
      - nginx  # Ensure nginx is available when service1 starts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/Apis/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5

  oj-evaluate:
    build:
      context: ./oj_evaluate
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/Apis/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build: ./  # Assuming your Dockerfile is in the root of your project
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - oj-evaluate  # Ensure oj_evaluate is available when nginx starts

networks:
  app-network:
    driver: bridge