# Generated by Django 4.2.1 on 2023-05-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('problemStatement', models.FileField(upload_to='problemStatements')),
                ('visibleTestCases', models.CharField(max_length=1000, null=True)),
                ('HiddenTestCases', models.FileField(upload_to='testCases')),
                ('correctSolution', models.FileField(upload_to='solutions')),
                ('correctOutput', models.FileField(upload_to='correctOutputs')),
                ('difficulty', models.IntegerField(default=1)),
                ('acceptedSubmissions', models.IntegerField(default=0)),
                ('totalSubmissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email@email.com', max_length=50)),
                ('name', models.CharField(default='name', max_length=50)),
                ('username', models.CharField(default='username', max_length=20)),
                ('profilePic', models.URLField(default='http://www.example.com', max_length=500)),
                ('token', models.CharField(default='', max_length=1000)),
                ('leaderBoardScore', models.IntegerField(default=0)),
                ('totalSubmissions', models.IntegerField(default=0)),
                ('acceptedSubmissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='submissions')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Apis.problemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Apis.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='tags',
            field=models.ManyToManyField(default='default', related_name='problems', to='Apis.tagmodel'),
        ),
    ]
