# Generated by Django 4.2.1 on 2023-05-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_usermodel_isadmin_alter_problemmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemmodel',
            old_name='HiddenTestCases',
            new_name='hiddenTestCases',
        ),
    ]
