# Generated by Django 4.2.1 on 2023-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_rename_hiddentestcases_problemmodel_hiddentestcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='outputs',
            field=models.FileField(null=True, upload_to='submissions/outputfiles'),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='tags',
            field=models.ManyToManyField(default='default', null=True, related_name='problems', to='Apis.tagmodel'),
        ),
    ]
