# Generated by Django 4.2.1 on 2023-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0005_alter_submissionmodel_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='testCases',
            field=models.FileField(null=True, upload_to='submission/hiddenTestcases'),
        ),
    ]
