# Generated by Django 4.2.1 on 2023-05-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0006_submissionmodel_testcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionmodel',
            name='testCases',
        ),
    ]
