# Generated by Django 4.2.1 on 2023-06-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0008_usermodel_hashedpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemId', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewedProblems', to='Apis.usermodel')),
            ],
        ),
    ]
