# Generated by Django 4.2.1 on 2023-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0009_problemidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='hashedPassword',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
