# Generated by Django 4.2.1 on 2023-06-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0011_alter_problemmodel_correctoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionmodel',
            name='outputs',
        ),
    ]
