# Generated by Django 3.2.19 on 2023-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0012_remove_submissionmodel_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='visibleOutputs',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
