# Generated by Django 3.2.19 on 2023-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0013_problemmodel_visibleoutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='visibleOutputs',
            field=models.FileField(null=True, upload_to='visibleOutputs'),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='visibleTestCases',
            field=models.FileField(null=True, upload_to='visibleTestCases'),
        ),
    ]
