# Generated by Django 3.2.19 on 2024-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0014_auto_20230821_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='request_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='status',
            field=models.CharField(default='Queued', max_length=50),
        ),
    ]
